# Generated by Django 4.2 on 2023-04-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fee', '0002_alter_plan_billing_fre'),
        ('accounts', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=40)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('no_of_participants', models.IntegerField()),
                ('no_of_classes', models.IntegerField()),
                ('shot_des', models.CharField(max_length=200)),
                ('age_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.agegroup')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='mem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.membershiptype'),
        ),
        migrations.AddField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fee.plan'),
        ),
    ]
