# Generated by Django 3.2 on 2021-09-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_des', models.TextField()),
                ('billing_fre', models.PositiveIntegerField(choices=[('#1', 'Daily'), ('#2', 'Weekly'), ('#3', 'Monthly')], help_text='Billing Cycle')),
                ('per_class', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('total_count', models.PositiveIntegerField(help_text='No. of Billing cycle to be charged')),
                ('offer', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.plan')),
            ],
        ),
    ]
