# Generated by Django 3.2 on 2021-09-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='billing_fre',
            field=models.CharField(choices=[('#1', 'Daily'), ('#2', 'Weekly'), ('#3', 'Monthly')], help_text='Billing Cycle', max_length=25),
        ),
    ]
