# Generated by Django 4.2 on 2023-04-28 11:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('classroom_id', models.CharField(blank=True, max_length=15)),
                ('class_room_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('no_of_rooms', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('participants', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('room_status', models.CharField(choices=[('#1', 'Active'), ('#2', 'Inactive'), ('#3', 'Removed')], default='#1', max_length=30)),
                ('room_id', models.CharField(max_length=20, null=True)),
                ('room_name', models.CharField(max_length=200, null=True)),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('#1', 'Sunday'), ('#2', 'Monday'), ('#3', 'Tuesday'), ('#4', 'Wednesday'), ('#5', 'Thursday'), ('#6', 'Friday'), ('#7', 'Saturday')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classroom.classroom')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_in', models.TimeField(auto_now_add=True)),
                ('log_out', models.TimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('clsrm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classroom.classroomtype'),
        ),
        migrations.CreateModel(
            name='BookDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, choices=[('#1', 'Booked'), ('#2', 'Attended'), ('#3', 'Enrolled'), ('#4', 'Not Interested')], default='Booked', max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='phone number should exactly be in 10 digits', regex='^\\d{10}$')])),
                ('date', models.DateField(null=True)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.agegroup')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classroom.timeslot')),
            ],
        ),
    ]
